name: Deploy to S3

on:
  push:
    branches:
      - main
      - destroy

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::123456789012:role/github-actions-brunoserraoliveira-pipeline
        aws-region: us-east-2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Initialize Terraform
      run: terraform init
      working-directory: ./terraform_s3_website

    - name: Apply Terraform
      run: terraform apply -auto-approve
      working-directory: ./terraform_s3_website

    - name: Sync S3 bucket
      run: |
        aws s3 sync site/ s3://formacao-devops-bruno-oliveira --delete

  destroy:
    if: github.ref == 'refs/heads/destroy'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::123456789012:role/github-actions-brunoserraoliveira-pipeline
        aws-region: us-east-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform_s3_website

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: ./terraform_s3_website